print("First programm")
print("added second line")
print("added third line")
print("added fourth line")
print("added fifth line")
print("vvce bangalore")
print("bangalore")
print("FDP")
print("EXIT")
